- hosts: all
  become: yes
  roles:
    - ensure-python
    - ensure-pip
    - clear-firewall

  tasks:
    - include_vars: vars.yaml

    - name: Setup swap
      block:
        - command: fallocate -l20g /swap
        - file:
            path: /swap
            mode: 0600
        - command: mkswap /swap
        - command: swapon /swap
      become: True

    - name: Install Docker
      block:
        - mount:
            path: /var/lib/docker/
            src: tmpfs
            fstype: tmpfs
            opts: size=25g
            state: mounted
        - include_role:
            name: ensure-docker
        - pip:
            name:
            - docker
        - docker_container:
            name: registry
            image: registry:2
            state: started
            restart_policy: "always"
            published_ports:
              - 172.17.0.1:5000:5000
      become: True

    - name: Setup http server for git repos
      block:
        - file:
            path: "{{ item.path }}"
            owner: "{{ item.owner }}"
            state: directory
            recurse: "{{ item.recurse | default(omit) }}"
          with_items:
            - path: /logs/apache/
              owner: zuul
              recurse: True
            - path: /webroot/
              owner: zuul
            - path: /etc/systemd/system/apache2.service.d/
              owner: root
        - copy: "{{ item }}"
          with_items:
            - src: files/apache2-systemd.conf
              dest: /etc/systemd/system/apache2.service.d/
            - src: files/apache.conf
              dest: /webroot/
        - apt:
            name:
              - apache2
              - gitweb
      become: True
